services:
  pdfding:
    environment:
      - DEFAULT_THEME=${DEFAULT_THEME:-dark}
      - DEFAULT_THEME_COLOR=${DEFAULT_THEME_COLOR:-blue}
      # use a long random secret
      - SECRET_KEY=${SECRET_KEY:-some_secret}
      # the domain where you want to access PdfDing, e.g. pdfding.com
      - HOST_NAME=${HOST_NAME:-10.10.100.12}
      # In production set the following values to True
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE:-'FALSE'}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-'FALSE'
