name: PdfDing Manual Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manual publishing
        type: string
        required: true
        default: dev
      branch:
        description: Branch for manual publishing
        type: string
        required: true
        default: master

jobs:
  manual_publish:
    name: Manual Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          username: mrmn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          build-args: |
            CI_COMMIT_TAG=${{ inputs.tag }}
          push: true
          tags: |
            mrmn/pdfding:${{ inputs.tag }}
          platforms: linux/amd64
