name: PdfDing Release

on:
  release:
    types:
      - released

jobs:
  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v.5.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # 3.11.1
      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: mrmn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          build-args: |
            CI_COMMIT_TAG=${{ github.event.release.tag_name }}
          push: true
          tags: |
            mrmn/pdfding:${{ github.event.release.tag_name }}
            mrmn/pdfding:latest
          platforms: linux/amd64,linux/arm64
  update_changelog:
    name: Update changelog after release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: publish_release
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.repository.default_branch }}
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.13'
      - name: Update changelog
        run: |
          python .github/workflows/scripts/update_changelog_after_release.py \
            --release_tag '${{ github.event.release.tag_name }}' \
            --release_body '${{ github.event.release.body }}' \
            --changelog_path 'CHANGELOG.md' \
      - name: Commit and push changes
        run: |
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git add CHANGELOG.md
          git commit -m 'chore: update changelog for release ${{ github.event.release.tag_name }}'
          git push
  trigger_chart_release_wf:
    name: Trigger chart release wf
    runs-on: ubuntu-latest
    needs: publish_release
    steps:
      # we need to use a github app to trigger a workflow in a separate repo
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ vars.PDFDING_APP_ID }}
          repositories: PdfDing-chartrepo
          private-key: ${{ secrets.PDFDING_PEM_KEY }}
      - name: Trigger release helm chart workflow
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api \
            --method POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
          /repos/mrmn2/PdfDing-chartrepo/actions/workflows/${{ vars.CHART_RELEASE_WF_ID }}/dispatches \
             -f 'ref=main' -f 'inputs[release_tag]=${{ github.event.release.tag_name }}'
